WebAppPersonalEjemploNuevo/Models/PersonalEnt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppPersonalEjemplo.Models
{
    public class PersonalEnt
    {
        public int PersonalId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
    }
}

WebAppPersonalEjemploNuevo/Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppPersonalEjemplo.Models;

namespace WebAppPersonalEjemplo.Controllers
{
    public class PersonalController : Controller
    {
        List<PersonalEnt> listadoPersonal =null;
        public ActionResult Listado()
        {
            listadoPersonal = new List<PersonalEnt>();
         
            //Llenado local(sin base de datos), al inicio cargan 2 registros
            PersonalEnt pers01 = new
                PersonalEnt
            {
                PersonalId = 1,
                Nombres = "Juan",
                Apellidos = "Perez",
                Correo = "jperez@hotmail.com"
            };

            PersonalEnt pers02 = new
             PersonalEnt
            {
                PersonalId = 2,
                Nombres = "Pedro",
                Apellidos = "Suarez",
                Correo = "psuarez@hotmail.com"
            };

            listadoPersonal.Add(pers01);
            listadoPersonal.Add(pers02);

            ViewBag.listado = listadoPersonal;

            return View(listadoPersonal);
        }

        public ActionResult Nuevo()
        {
            //TempData sirve para enviar datos de la view al controller
            //A diferencia del ViewBag que envia datos del controller a la view
            List<PersonalEnt> list = (List<PersonalEnt>)TempData["listado"];

            PersonalEnt persObj = new PersonalEnt();

            ViewBag.listado = list;


            return View(persObj);
        }

        
        public ActionResult Registrar(PersonalEnt persObj)
        {
            List<PersonalEnt> listado = (List<PersonalEnt>)TempData["listado"];
            listado.Add(persObj); 
          return  View("Listado", listado); //Una vez cargado
        }


      
    }
}

WebAppPersonalEjemploNuevo/Views/Personal/Listado.cshtml
@model IEnumerable<WebAppPersonalEjemplo.Models.PersonalEnt>

@{
    ViewBag.Title = "Listado";
    TempData["listado"] = Model; //se envia el listado en TempData
}

<h2>Listado</h2>

<p>
    @Html.ActionLink("Nuevo Personal", "Nuevo")
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PersonalId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Correo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PersonalId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Correo)
        </td>
      
    </tr>
}

</table>

WebAppPersonalEjemploNuevo/Views/Personal/Nuevo.cshtml
@model WebAppPersonalEjemplo.Models.PersonalEnt

@{
    ViewBag.Title = "Nuevo";
    TempData["listado"] = ViewBag.listado; //El ViewBag trae el listado del controller
}

<h2>Nuevo</h2>

@using (Html.BeginForm("Registrar", "Personal"))
{
    @Html.HiddenFor(model => model.PersonalId)
    @Html.LabelFor(model => model.Nombres)
    @Html.TextBoxFor(model => model.Nombres)
    @Html.LabelFor(model => model.Apellidos)
    @Html.TextBoxFor(model => model.Apellidos)
    @Html.LabelFor(model => model.Correo)
    @Html.TextBoxFor(model => model.Correo)

    <button class="btn btn-primary" type="submit">Guardar</button>

}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebAppPersonalEjemploNuevo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>